[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "c3ddd25e54eead1a0c8f65f340b34d131e34c010"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "6410abb0b813b325f0ea558f1c0b8cf4ed152f048ef769bc9d94e1e44e33e863"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.arm-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "9dbbcffa22fff270e011d7b6a97d51e725c1b3d4"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "f989204a7fefde8fe7796ab7b6bb2405dd7914733fe953c438ef727de52cda14"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "e4337cdffb99dbcf113b39005f2bf8cf930f47b2"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "c998a89a657ff6ffb93e060b138edf92971faa78ef554c54860eeeb00d988c71"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "9ac8135df2cc6e8cdd67e825d6cfe367a29ed603"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "6eae8946f3023c2a440d67891154175ca707b75bb7efb9d5d609a84adf171ed6"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "4c458cf5158acabf33ea83c039fcf82ad692aa21"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "aac284431de328420bd19381a5122ef34d28f7c6c11cceafd5d97845a6858383"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.x86_64-apple-darwin14.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "28cf43c6053481c131a298bb45a355e77fe90d16"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "710952746364f323ed416ee151620efe66705b126beec179ae0aab4c8ff3c74f"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.x86_64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "92eef98b3c16728a452cab1deffa784c7cfd3bab"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "1c93dc743766ce656357f1210dd8914d4841f9d1448c483a02d06c5221fac2c6"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.x86_64-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "995563ff2ffbcc7c0607319055176ffe2777c05d"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "8c6b042ff17e348d75bb3508666df03b9594ef16930170a2472fd937764e93d1"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "fae64fcbdafa98378ff54db73d0db445368e002c"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "75f72643be73c958161cb7d32a17f3f39f59a42a20522971f17db0dbef4c71c6"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.aarch64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "7214d9070df579d67c5acad996fbb6bcdec7ff9d"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "0e0f83c950830ccddeca06494b42a70db9fa0e30ce2557b4158b7372c65d424f"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "13bd2877c3d84de8162c8d435ec63a8e76e07394"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "4e32f70ec0ddf89cc3554835d01843a277e221a318cd6b285ef55dd95e3fd2b7"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "ecd63e69e6415ffbafc736056b86ca0e42869194"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "7e87210bc991347ce8323268629165250e18dc096fab558757381da0cacb543d"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.i686-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "437778f0d956cc003f6419ca8199e9d63e568a81"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "a4ed066489cffd98e0dbb7294572c593229aaef56d61551783b227f1b93562d8"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+8/Fontconfig.v2.13.1.arm-linux-musleabihf.tar.gz"
