[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "2a5982fc5a9182a3acb192fa29305f672fb4c044"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "330199469ba4628edbd0e5371380af6c5f97c22a2831c473e2cf5c2b84a614bb"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "0b92772034674871b72ae6eb965e8ef7845d9425"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "5e6b9dc6089bee77d320e82fe8db95e2ca83e7b5d51d3e848097a87d253b74ab"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.x86_64-apple-darwin14.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "03bc0c5d78a9f73006e2e5728419e883b165d30c"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "42c3e6fbdc1cc0a047032f373a5800912dd184e4285304eebb173ec014726c29"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.aarch64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "ec5f09616d6ed9e1fc5ff369fc4cb34b045e1b8b"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "0df356829860ca50524e4b85c42b379b7db723e7ad9be0e5c8d9593c3cd6a08e"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "4c94fa4e6362d805fcecba387a5e658a38dbf034"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "8a6a787214de9cb9696dc97d3d982a4b182e86c20beb9d1251c73ef4ccb4d355"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "5137b9632d45c462b1051112f4e532a1ffa76907"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "85a988df254d812100db4033856203ce15835468f2b64a6e666b51ee78abfe5f"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "1226aefcda545193e358e5fa1ca4eaf37a0d9719"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "87550c2b93fc3fdb40e939a6de0f5b595fe011d84c7e38a65d2f6179731e2dd3"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.arm-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "67b6f095d73f0253e3d3bbafaf76a6eb264b9145"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "3a93b92d9665ba507f06f22ead2f067a0ed87d38c0235ea2feb758ae3e437adf"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "b44fe45351e47b18aa9e41d2a85ce80abf8735be"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "9920c39fb220f9ff5ab8b908a4af46a31c6d03d149335ea6e12a31f07339609b"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "535e4744204c223864c9b9e5a275577072328287"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "6adbeca056da8bcee647336bd66e7ab6366531f8f43707e2f550c3000b419342"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.x86_64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "9188661172b30377755fe50a64ba8b049887a1bf"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "81b4412fe9ea07367b3fbd9adbd9b392b4e5a91e3d792643d9df5fb34f7523b6"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+2/Fontconfig.v2.13.1.arm-linux-gnueabihf.tar.gz"
