[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "e50545ead136aa5d58eff4388fc002278ac6aec7"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "0de7d0a9edae7c8333805ba89a49bd4810e6ddccf626007d0174fe4731388824"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "40f2c2553ba59ee72d44d40333f340df8e19dd43"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "64c3808911863d46677ee97928639e615df045ea41a6c12b9a5bc7ce5306a3fc"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "c6f53b0adfb48f611ad41b73461d9419117d3503"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "d0ab48a565eaf66abe500e843d75a6be53b184a6dfd139491520b2426476da00"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.x86_64-apple-darwin14.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "b6ff197255deb84f724ea2ecdce0179ca57b1b03"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "7038cd572dba305467b788085d27b4c36cb19e4f4e730688503804e0d8315f81"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "50d294bc2e5e61436e2df52495150588e77ba904"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "1683e823f341527178068675a8ed4b733f58df8434ddb3ff2dcf84d0afd9c958"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.aarch64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "2c640270f2efa614928a19b065392d2c548d9ea4"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "e87e3329f40de2b3972019d6f41eb99b38db1d26cd2c011df651851cefae8953"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.x86_64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "769f063becbfd0a63c418871a13b4d9293a3be46"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "41aab8f6e11b9c6cfc0006b7183c2f17b58c0af9ba8c35a1dc2ee61a8d74d422"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "8a14057a22ad0db33c66b33f06dec80fb63904d3"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "12ffb36eccb6163e10ea39e136f98d19d666ad669a7cabca0cdbd408a4250f4c"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.arm-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "deae2d91c6d050fa7425526f7ec60542f9f787fe"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "476074c979170bf1d24c1afbad77fafd622813d2efa61879044f60cf4f8ba165"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.i686-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "4d2b0df4b67c11e78c65936918bfa492ae881fca"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "3d53691c99a71c50c68dfe71f766cf31fbfe6326fee82ac59fce9a02383ab1d3"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "210eb046fb4fe1638210f1cc6efc79074e5a773c"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "dfc7cafe0dafe0cb55f178fbed2b4383028ddc81388a3e5a62070fd919ee1c58"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.arm-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "202782b3ef5348aedb3a56fce989549dd15315cb"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "0e6fec96e6585c16a154295a735db601bd8960328961bfe724ec1d6724e9c66b"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "4747999bd54f8572e3cdd5aba7341b6201b85f05"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "b06a4080a8ff0a323b5849e979d7e10eba48b557b35bde813f4c418364bc650f"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+10/Fontconfig.v2.13.1.x86_64-w64-mingw32.tar.gz"
