[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "c76ab6853b970207e645b7e0c72d9752050a6520"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "0eefa8be37bc8295572124c4556a595209f1898e0c47c7ea2db825b8c57a9936"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "8c71f7a2a987d5f9c3912b7b8046a598920723bf"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "afc4c498503f713c26d4d1ea1a4d290fec2cfab4e0eda4a230de3dde9fe7a6c4"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "a0a8b38401f247c27cb5428153d2eb9d4c767d32"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "b270a6b278942f6df159ef2f4c557d01c52a2d92c204ad087084d68bc51ead60"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.i686-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "3256b8a6d46e9072de141564d4ce9544e74bef7c"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "7419a99d5793dcdd6c71ea539a0c781fda5e3303ffb810e5549e5b1955d64f61"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.x86_64-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "d67a29bbdd75f49aa4329ca87a6b32859d010049"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "25ab3691fdfd80e04a0f3ddea0cfab992fcc99ee1afb08d4dc523e1e94eeb17b"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.armv7l-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "d2661351a69cc0277b3fc9228542ab44deba7e75"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "e3b3ab8a2a8b40b9c86350d7957262021cead635c9cfca320532f432cd5c635f"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.armv7l-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "71320dacb1a064d1d6eebf5050f00f40bba4ec8d"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "2d408043e01907cd451ce58bdb5b66d20647cea784a33068b18045920e284ccd"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "82f1062ef35feaa6d4cc426c15574338f12f5fd1"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "589e143c748f921161d96de0998bbf39630578c617128824333cbdac0b82f6ba"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "3ff2d0ff8d907cf8a74c5e29b81584d33b6ef2a4"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "b9e4c5d25cba701c76b4b836837ae1aff7c433d914595fbbea98558d422df2fe"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "bbd798da2abdc8bcb544304f0f2cf22f88abb14d"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "92d0233c3991c7866dabf3365b040fd018546b410e20c0399fe78b0ee28c84a9"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.x86_64-apple-darwin14.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "f5813c4ef2103c9e5d3bbecb07f2e872b0d9ae6f"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "81c8616214d0948d3e7d1a23bfdbc6b0890ca0d916f7787daf0e9f110144f785"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.aarch64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "f19b72be5a424f10b90c36ae30d433456b917ec0"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "36df6a895b1e9186e91ada44a8b5cffd1b68dfa81c7d179e37300c39e042965c"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "6f0bb281f199a9fcddb8a67aa80a8b827cca37fc"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "58f8200375153c5ccebce34ccc0c20270ea323af78c10df37a52648e45769096"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+11/Fontconfig.v2.13.1.x86_64-linux-musl.tar.gz"
