[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "f00ec04851ced5895bd99297d49916ba59ca783d"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "afdbc96de19c1f1f3abc7fd9c85dfdd6da8fbe9a9da420defae37278dceb87ff"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.aarch64-apple-darwin.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "1d982b41bfa3bcdf679e8021d6003e596a3f3210"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "b797ba7fcf6ecc2ab0390af42f4f84f8777303ffe157059468c24f86d6946c18"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.aarch64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "6044ecbc8f25883f603d6878a7ae8250df428e5e"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "6ef4001132a4af755ac17dcf1137a0597a72c08da8c4d52451f8667510aa2ed2"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "ec6f6071436bd9015687a97d1dc7ea7d08450eeb"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "dbb3d91d6e301d017d59c8568af27be1730f0be59892e63be7fceddd69277b86"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.aarch64-unknown-freebsd.tar.gz"
[[Fontconfig]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ceeb81e033f6f608bde8363dc5a59d2f85ab694"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "710bc694667351c35abf6200d81077823619f1a23a4043a7e6ec90be058e8a0b"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.armv6l-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "caa62f1e3829af3b95f82d52f342d7b79361d6be"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "71afb91cc9be57a47ba3eb840dc439a9c0d8fc487f413df1232bb1ba9a524c7d"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.armv6l-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce0924470037bbde557cd47c9c94585d638d6430"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "0fed91bcf25903eb23badf2e9749000b6a7af587066d616158d96e4979a0b167"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.armv7l-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9b8de2619f505dc1683012061f2471f8fcddce5b"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "27d01cd01ab79d16ed44853ec53236f526bad79d2855a72fa8d028c6c9d06383"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.armv7l-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "69946cf7b2ec12d488a3c6ebf217a01addf73925"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "f330298be5ea307c71d98c29eeee327f0a86bbbd874a671fc32fd6daf3cc6dd2"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "fcc1057356b5657da1d979bc97fc5c1496eadd99"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "49d842254daf3263c03569dd6bc05a5d5280b371f8476867f74603a4a1684432"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "e61478c7e010136d396d18e403adb3c6281a89e3"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "2535bd8abab9dee7ae040ccad7fbd703916198a892dfb3e59e35dd426c492115"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.i686-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "6bcc95480086716a533f653ef49715a795a6aa78"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "7f5c55e047d417c8b6b74ace4d0730782686f5f4c2269fb56512bf7047fec6b8"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "riscv64"
git-tree-sha1 = "fd572df4564c212f04b170abe4bced15d3f2d048"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "4c4428721e77c0e7ce1025f47eb59ee0433dfae610c5b63e704a6b9a92f4a016"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.riscv64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "7629392c0943870b66003a9732357d60cbdbc350"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "0e1f79de27d94be7a24587623b584612478fb4b589f56ec0a796c87ec855e738"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.x86_64-apple-darwin.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "2a6bae048c28452d329375cbb7479499115e45ad"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "882ff96fc73271a986ac7b045b683ec51170106686fbc651f2ef81fdb60d6b73"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "9119f1203626d288ec017f0173ef633cc45fe4e0"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "9e54b357f3f02c0d1cd47529493d5fec369e82674aee3b06dba31c9c1171dcd3"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.x86_64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "2ecaafe61d3cc1914ae448058ea6f68a26a10106"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "340e5e7a8e138ff7574330cc62042a880f6171287e82904eca76e3b973ad9b73"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.x86_64-unknown-freebsd.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "7a0bb5e45d4299e0335822c903fe5bb9ffe32fdd"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "29b14ad84050a17284943a50fb4c72ab5d0204db6d0de9ec4db8b6c8f0da034c"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.16.0+0/Fontconfig.v2.16.0.x86_64-w64-mingw32.tar.gz"
