[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "886df745cefeb82992e03223358349fb95adde15"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "d3cb8975207a45f31dddc868a77f53803831e9db590b9ae2dbb03b65e1063af1"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.aarch64-apple-darwin.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "e1ad70fa680940f8a94387342a2fb2a8432e19aa"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "0c05668eb1e7cfa5f8f347941c5dc0ee96bf9ab27e3bda4073df869d3f8d9f17"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.aarch64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "c970cfbc8a1bfc3a7a0e3220cd64075f518ee207"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "8a3383a4dbf8c9e7d7fc96544ba48507a82229df6d3f6a961d931bd01194d1bd"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "f1811860f36d8face94940fd4ad5fade05926f00"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "15f055ca998be00e0056f754153b57c6b840fefa0e9d9fdd79eb89d322778c17"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.aarch64-unknown-freebsd.tar.gz"
[[Fontconfig]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e031a93daee5271080f2bb771954148356df39c"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "51af9df9826a05a2722c9248be9075d7eb36f8b907dbffa8420db71dfbd1fc23"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.armv6l-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75978d7f719738976b5ca8b007e070959d8f67ba"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "e7fa3363b4fff442b42456a170b27d3725da292f29f9e86ff0586064e30788f9"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.armv6l-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "061b287bd29dae39b4448839ca1ea4973773727d"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "ceea4419baacc2312311a663801d2e4ed9be128f80c0ccaeafa78507b8656e6f"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.armv7l-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c875f2eff6d507102bc3230101a15ac4ac7b319f"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "a5aeaaf117971923a3858ec6939e73ea046daa8b23c4ccd02ae51c6a59574209"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.armv7l-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "af34d630b67c8aa7a032051c0c98b6bf8645547b"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "833aaae8d3fe08f933de4d5b66ba78746717c9dca984a35a40c41acff5b532d5"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "5a88488f275688344f558ba71a98ecc079bbc71f"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "d37ca50bdf4a759378efe8eacd0810365c569a0e7eaa9dbfe96ed53899f3fbf0"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "ea8ab029f5f131308b1b69a4c73942b56443bf79"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "cc7dbc1b32928090a3d16399eb1f314392a2ddd75ed59c6d82efcc3dec0c1a5a"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.i686-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "5e5ba445e98fbd79276a8689ddf52a4471f982cc"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "37cf93f0fd33b463fc824a848c69f7b8c15b549e8ce0541905853b04360fb1ea"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "riscv64"
git-tree-sha1 = "ab909c948301c41182d883da4edb434a84e606ea"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "6482efbc68d98bda834b48cf8b79c11f383ffaaa773a761e9fbf081ae2f63e80"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.riscv64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "345771aa0675d20b2902f32ce82bb747d88f2a11"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "cba5372e77eee5f8dc725a2047c1550a62499b30dc1a8607ec2f292f2240babb"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.x86_64-apple-darwin.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "258f7271ca555a7634c0fe8b8508f69334673a89"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "17e7118ffcf7ba325520c92979311ea542e39d6d632a4b234186eb4e6878e11d"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "e2f80758f8401d8b0fa01ad6a2422089eb5b19b0"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "039338b60db0da88ff6d858e13ab01d4ff86390d231203f31b1805f72df9ebdd"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.x86_64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "2b8607c4a5b50746814ee74e8980e53d6bb73ec2"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "6ab0fc1d87940ffd63bdda6c2e0eebec9b880ccdbaf6995a36d0684c8f67557a"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.x86_64-unknown-freebsd.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "cb74fa09f359d430ea01be69a61cd98b50ec8c22"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "ad758994770c2607b75d41cf2c77105e455274ef50d646c7a6971cfe63cfb5c1"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.17.1+0/Fontconfig.v2.17.1.x86_64-w64-mingw32.tar.gz"
