[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "c18a9eb76009a2281159de1b643f8f92d9baac4a"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "baee258cd58584d7dec41dffe38832ea8ec3fc1a7f52da55eb1cef6481cd59b8"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "37441acc9f274156972fe451c6722a6909a049ee"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "f50df2227f9d9383d6d4e64ec261fe33fd27055ba882b4112c4de973bf4e54dd"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "c47bf814d498c3422f3ceebb2c86a5691ff470ae"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "44b7a07466ed8e45f58c08c290d4c53d2f5679abd4f2b4caab3bfa54fa0e09a4"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.x86_64-apple-darwin14.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "a4c4fb21589c1fb4a8d1a7597732d1f8ee340b92"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "06a425b39c9828bdd88e2e2f41e13dc4649469e9ca95f18c2c01e96bf609e404"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "db5637b1bb4da049b645cb7d0aafd736a89068ac"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "bb8f978057e5711bf5819f2b401827188afdc55b992be8814f020007df511bbb"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.aarch64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "ec7baf3846204519e17204a87d5e698b72d28b35"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "74ebaf59a25011c81c559c5ce35f3e81812b4fe04ea2961f8caf7d7df7cae721"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.x86_64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "f386652d96573c7a1ce58b2cfc97b13739265489"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "dafa37550149475df00e3a66f19e3a9236648bf2a90ee683ff1fc2891038fc52"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "497777705f92f0f7ea97e78a906ae85455e8ce0f"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "96be536f9fc87164b501122e248ed4f86e9ac24640bd5a2ba4fd277ed8b832ad"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.arm-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "1d83eb696985c4b1b1c7aa59b901684fe1e9dc7c"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "6517ae64b025473b1fd65628739132d0026788b98432b280a80b48da4b09910b"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.i686-w64-mingw32.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "ce095f802b68725ee1ed7db5e1746a7bc96dc060"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "fbfb7bea71d0a75682162d534fa5027bb123ea9182c05bda702d2838e2dc5499"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "183cc14480e0e384816b873cdc2fc8281237e683"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "df5a2d82ff9afa3786eaa8ae33bc62e62cef57e1618b87df11cfd151c21b6edf"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.arm-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "b20d3b4e71d9209bc0d83410b048e97b4f8c7096"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "520a3bfe8eec51d87a7b37ab9b78be13ac89d0c000ae788f7bf8d2b74a40a2be"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "3c80e628d6bd544f8fa394e168c241726bdf440b"
os = "windows"

    [[Fontconfig.download]]
    sha256 = "15ad1afb3af3c504b2958ae46ebd6c91d33a1608dcf56451e597890e2aef9588"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+9/Fontconfig.v2.13.1.x86_64-w64-mingw32.tar.gz"
