[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "ede04a182bb69c81957ddda01c5c77a9c5d67ba2"
os = "macos"

    [[Fontconfig.download]]
    sha256 = "a5cd57aa76561cf6d258cfed6ea0ecc4e375e5e9c7048d083dc46ab877252ce2"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.x86_64-apple-darwin14.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "1d68f42b8238b62c904295d589f4a4232a409cfa"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "6150412da722f0a78eadf2b6073d72974e9905a85d75a43ca784ed0f73a26744"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.i686-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "6fb07fb82803b37653bf16009e21a0ca57393775"
os = "freebsd"

    [[Fontconfig.download]]
    sha256 = "746892e562c2aa7f781cf8175bbb70a185fccc4ac904b3802ce7f2e10b49f3dc"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Fontconfig]]
arch = "powerpc64le"
git-tree-sha1 = "20cd47b6aa7cb6a7399bf6d4f16b4945e6cd9b78"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "4ddae51e1738eb3c4fb6f14877cbfab4e18cc729f1a36260e4d5c3e0d787194b"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.powerpc64le-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "360cb3cc4ba90a57ba63528aab03d3038efc9e4b"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "cf512937af02d8521682b2215b6d16d7c6a60892e2e8e662b2853a4ef3e414f9"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.x86_64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "x86_64"
git-tree-sha1 = "8e61bb9c5266444fc104d0c5b648fe066c5f067f"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "203969dc275714cf40fa08b805ad7898195d2e4d12c4b10b83ae0ca325d373f3"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.x86_64-linux-gnu.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "0a2561a019c529e92411cb9dda28bba62626c288"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "26c3a643ca1a14abb9121459c836cd98445c8475bb139e7805c9fdc90df7a6d1"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.aarch64-linux-musl.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "bea31c1ad9c11b936f036cc50263dcedae95f500"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "55156ace2fec550c58b759f62c7ebd29828aca0ce95f7267a93dbae28b73b07e"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.arm-linux-gnueabihf.tar.gz"
[[Fontconfig]]
arch = "i686"
git-tree-sha1 = "0e19a1fb656126581c0b4da88815983305123340"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "be7df953a9f43b03bc62b7c5333bdb1083a961565b629c855fa2725cfee5a273"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.i686-linux-musl.tar.gz"
[[Fontconfig]]
arch = "armv7l"
git-tree-sha1 = "17d24336fd3319ee56b36d1b98f349c5ebbce0b4"
libc = "musl"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "8e610c31e94d78e67420f9acaaf5603d69e15166427e8c602af09c8d2979b274"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.arm-linux-musleabihf.tar.gz"
[[Fontconfig]]
arch = "aarch64"
git-tree-sha1 = "4be5704e860571b90f339c2049c21b14e6f94ef6"
libc = "glibc"
os = "linux"

    [[Fontconfig.download]]
    sha256 = "1b4a1c5639ecfeaa6ee7231d0dba6e28665142581afb148d90d179b2e859a754"
    url = "https://github.com/JuliaBinaryWrappers/Fontconfig_jll.jl/releases/download/Fontconfig-v2.13.1+5/Fontconfig.v2.13.1.aarch64-linux-gnu.tar.gz"
